### ISSUE TITLE
The purpose of Line 588 in the transformer_wrapper.py

### ISSUE THREAD

**Issue by Yuran-Zhao** [mt-upc/transformer-contributions-nmt#1]
Hi Ferrando,

I personally find your work very interesting and thanks for your efforts in providing open source code.

However, I'm a little confused about the purpose of [Line 588 in the transformer-contributions-nmt/wrappers/transformer_wrapper.py](https://github.com/mt-upc/transformer-contributions-nmt/blob/0af85383f211238f23a5a693730a79634d89bf66/wrappers/transformer_wrapper.py#L588). Why can't we just concatenate `self_dec_contributions` and `cross_contributions` directly just like Line 589?

**Comment by gegallego** [comment]
Hello Yuran,

Thank you for working with our method and reaching out for clarification.

The line you're inquiring about corresponds to the computation of the "full decoder layer contribution matrix", as detailed in the closing part of Section 3.1 in the [paper](https://arxiv.org/pdf/2205.11631.pdf). In particular, it's associated with the process of "weighting every row of C_{y←y_{<t}} by the corresponding value of the residual contribution of each time step".

If you have any further questions or need more detailed explanations on any aspect, please don't hesitate to ask.

Best regards,
Gerard

**Comment by Yuran-Zhao** [comment]
Hi Gerard,

Thanks for your quick reply! It is clear now after your explanations :)
